apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- cluster.yaml
- control-plane.yaml
- workers.yaml
- addons.yaml
patches:
- path: ci-version-patch.yaml
  target:
    group: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: .*-control-plane
    version: v1beta1
- path: alpha-gates-patch.yaml
  target:
    group: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: .*-control-plane
    version: v1beta1
- path: md-0-ci-version-patch.yaml
  target:
    group: bootstrap.cluster.x-k8s.io
    kind: KubeadmConfigTemplate
    name: .*-md-0
    version: v1beta1
- path: md-0-kubelet-gates-patch.yaml
  target:
    group: bootstrap.cluster.x-k8s.io
    kind: KubeadmConfigTemplate
    name: .*-md-0
    version: v1beta1
