# This first Azure-specific machine pool implementation drives the configuration of the
# AKS "System" node pool to schedule and run kube-system and other system pods
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: "${CLUSTER_NAME}-pool0"
spec:
  mode: System
  sku: "${AZURE_NODE_MACHINE_TYPE}"
  name: pool0
---
# This first Azure-specific machine pool implementation drives the configuration of the
# AKS "User" node pool to schedule and run user workloads
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: "${CLUSTER_NAME}-pool1"
spec:
  mode: User
  sku: "${AZURE_NODE_MACHINE_TYPE}"
  name: pool1