# We provision a default machine pool with no bootstrap data (AKS will provide it).
# We specify an AzureManagedMachinePool as the infrastructure machine it, which
# will be reflected in Azure as VMSS node pools attached to an AKS cluster.
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: "${CLUSTER_NAME}-pool0"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: "${CLUSTER_NAME}"
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: "${CLUSTER_NAME}-pool0"
      version: "${KUBERNETES_VERSION}"
---
# Deploy a second agent pool with the same number of machines, but using potentially different infrastructure.
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: "${CLUSTER_NAME}-pool1"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: "${CLUSTER_NAME}"
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: "${CLUSTER_NAME}-pool1"
      version: "${KUBERNETES_VERSION}"